Random suffix to s3 bucket
npalm/terraform-aws-gitlab-runner pull request #252
Opened 2020-09-01 17:45 UTC by fliphess

Hey Niek! 

Feel free to reject this if you don't think it's useful :) I needed it to quickly recreate the module multiple times without having to change the bucket name in every run 

(as a result of testing some cloud-init userdata changes in our setup).

#### Description

This change adds the option to append a random string suffix to the S3 bucket name. 
As bucket names can only exist once, it's not possible to destroy the module and reinstall after without config changes as the previously used bucket name is not free for use anymore after teardown.  By adding a random string to the bucket name this problem is solved.

This can also be useful if you want to use the same configuration for multiple regions.

#### Migrations required
NO - Not if `cache_bucket_set_suffix` is not set to true.

#### Verification
Not yet! Will test later this week. 

#### Documentation

^ Is this stil actual? I could find the directory anymore. Otherwise I updated the README.md.

2020-09-01 20:59 UTC, kayman-mk commented
Shouldn't happen too often but makes life easier. +1

2020-09-02 08:07 UTC, npalm reviewed
Looks good, will run a check in the next days

2020-09-06 12:21 UTC, npalm requested changes
Just a few comments

2020-09-06 12:21 UTC, npalm commented on modules/cache/main.tf
> +  cache_bucket_name   = var.cache_bucket_set_suffix ? format("%s-%s", local.cache_bucket_string, random_string.s3_suffix.result) : local.cache_bucket_string
Variable seems missing in the variable.tf

2020-09-06 12:21 UTC, npalm commented on modules/cache/main.tf
> +  length  = 8
Please can you add here a count so no changes are suggested if suffix is not used
```suggestion
  count = var.cache_bucket_set_suffix ? 1 : 0 
  length  = 8
```

2020-09-06 12:21 UTC, npalm commented on modules/cache/main.tf
> +  cache_bucket_name   = var.cache_bucket_set_suffix ? format("%s-%s", local.cache_bucket_string, random_string.s3_suffix.result) : local.cache_bucket_string
```suggestion
  cache_bucket_name   = var.cache_bucket_set_suffix ? format("%s-%s", local.cache_bucket_string, random_string.s3_suffix[0].result) : local.cache_bucket_string
```

2020-09-14 18:51 UTC, npalm commented
@fliphess did you already had time to have a look on my comments?

2020-09-15 15:20 UTC, fliphess commented
@npalm Hey Niek, Sorry, for the late response, I'm on vacation for a few weeks so not working much on terraform at the moment, which is why I didn't do anything with your suggestions so far yet.  It is on my todo list at work. (This is my last week, coming Friday it's back to work again)

I'll fixup the code with your suggestions in the beginning of next week if that's okay.

2020-09-16 21:44 UTC, npalm commented
@fliphess enjoy you holidays

2020-10-08 20:20 UTC, npalm commented
@fliphess just a kindly reminder. If you have some time would be great if you can fix minor comment

2020-10-09 09:24 UTC, fliphess commented
@npalm Oh thanks for the reminder! It completely slipped my mind! 🤦  
I've just pushed your changes and rebased on develop. Let me know if this suffices!

2020-10-09 21:49 UTC, npalm commented
@fliphess thx will check asap

2020-10-10 13:21 UTC, npalm requested changes
@fliphess variable name in main.tf of root module is not mahcing, created suggestions in the PR.

2020-10-10 13:21 UTC, npalm commented on modules/cache/variables.tf
> +variable "cache_bucket_set_suffix" {
```suggestion
variable "cache_bucket_set_random_suffix" {
```
Variable name is not matching the variable used in the main.tf of the root module

2020-10-10 13:21 UTC, npalm commented on modules/cache/main.tf
> +  cache_bucket_name   = var.cache_bucket_set_suffix ? format("%s-%s", local.cache_bucket_string, random_string.s3_suffix[0].result) : local.cache_bucket_string
```suggestion
  cache_bucket_name   = var.cache_bucket_set_random_suffix ? format("%s-%s", local.cache_bucket_string, random_string.s3_suffix[0].result) : local.cache_bucket_string
```

2020-10-10 13:21 UTC, npalm commented on modules/cache/main.tf
> +  count   = var.cache_bucket_set_suffix ? 1 : 0
```suggestion
  count   = var.cache_bucket_set_random_suffix ? 1 : 0
```

2020-10-12 21:29 UTC, npalm approved these changes
@fliphess thanks!

2020-10-12 21:29 UTC, merged