Master
npalm/terraform-aws-gitlab-runner pull request #258
Opened 2020-10-06 10:52 UTC by wojukasz

## Description
Ability to attach additional policies is quite helfpuf, for example if one would like to use gitlabrunner to build golden AMIs.

## Verification
I have tested proposed changes and was able to deploy and attach additional policy successfully.

2020-10-08 20:36 UTC, npalm requested changes
@wojukasz thanks, just a small comment. Can you fix the description?

2020-10-08 20:36 UTC, npalm commented on variables.tf
> +  description = "List of policy ARNs to be added to the instance profile of the runners."
```suggestion
  description = "List of policy ARNs to be added to the instance profile of the gitlab runner agent ec2 instance."
```

2020-10-12 09:19 UTC, wojukasz commented on variables.tf
> +  description = "List of policy ARNs to be added to the instance profile of the runners."
Thanks, corrected.

2020-10-12 21:30 UTC, npalm approved these changes
@wojukasz thank for you contribution

2020-10-12 21:30 UTC, merged