feat: additional config parameter asg_delete_timeout to configure the…
npalm/terraform-aws-gitlab-runner pull request #305
Opened 2021-02-22 13:40 UTC by lukasmahr

## Description

To gracefully shutdown the GitLab runner, the deletion of the corresponding AutoScalingGroup might take more than the default timeout of 10 minutes.
Therefore, I added another config parameter to be able to increase the value accordingly.

## Migrations required

NO - default value matches to the [Terraform default value](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#delete)

## Verification

Tested in my local environment.

## Documentation

I added the new config parameter to the README.

2021-02-23 16:11 UTC, npalm commented
👍 for your contribution, will check asap

2021-02-23 22:24 UTC, npalm requested changes
Change is perfect, but README had conflicts, please can you rebase the PR?

2021-02-23 22:24 UTC, npalm commented
Thanks for the contribution, just one request, see review

2021-02-24 09:15 UTC, lukasmahr commented
> Change is perfect, but README had conflicts, please can you rebase the PR?

sure, should be done :-)

2021-02-24 20:42 UTC, npalm approved these changes

2021-02-24 20:42 UTC, merged