Conditionally create docker machine security group
npalm/terraform-aws-gitlab-runner pull request #351
Opened 2021-07-28 12:17 UTC by mhulscher

## Description

I would like to be able to configure the egress rules of the docker-machine security group. This PR introduces a new variable called `docker_machine_egress_rules` to configure these egress rules. It defaults to allow all egress traffic to maintain backwards compatibility.

## Migrations required

NO

## Verification

Ran a `terraform plan` in the `runner-docker` example.

## Documentation

Ran pre-commit with latest version of each tool; this also re-generates larges portions of the README.

2021-07-28 21:31 UTC, npalm commented
Please can you check the failing CI job, the modules is still on version 0.13.6. Assume you have used another terraform version. We use tfenv ot set the used terraform version.  Examples are verified with multiple terraform versions

2021-07-29 08:41 UTC, mhulscher commented
Hi @npalm ,

It looks like `terraform fmt`'s opinion about what is correct formatting has changed since terraform 0.13.6. When I run `terraform fmt` against my current PR, terraform recommends that I remove the whitespace between the character `!` and the next term in a negation. However, newer terraform versions recommend the exact opposite.

```sh
❯ ~/.bins/terraform-0.13.6 fmt -recursive -check=true -diff             
main.tf
--- old/main.tf
+++ new/main.tf
@@ -38,7 +38,7 @@
 }
 
 locals {
-  enable_asg_recreation = var.enable_forced_updates != null ? !var.enable_forced_updates : var.enable_asg_recreation
+  enable_asg_recreation = var.enable_forced_updates != null ? ! var.enable_forced_updates : var.enable_asg_recreation
 
   template_user_data = templatefile("${path.module}/template/user-data.tpl",
     {
@@ -125,7 +125,7 @@
       runners_root_size                 = var.runners_root_size
       runners_iam_instance_profile_name = var.runners_iam_instance_profile_name
       runners_use_private_address_only  = var.runners_use_private_address
-      runners_use_private_address       = !var.runners_use_private_address
+      runners_use_private_address       = ! var.runners_use_private_address
       runners_request_spot_instance     = var.runners_request_spot_instance
       runners_environment_vars          = jsonencode(var.runners_environment_vars)
       runners_pre_build_script          = var.runners_pre_build_script
```

If I update `main.tf` to please 0.13.6, newer versions will start complaining. Do you have any suggestions what to do with this?

2021-07-29 21:25 UTC, npalm commented
Please update to please the current TF version for the module, I will upgrade sources and formating asap to a newer version

2021-07-30 11:24 UTC, mhulscher commented
@npalm done!

2021-07-31 09:18 UTC, npalm requested changes
Made a small suggestion for a change. Furthermore there is a small migration required. I ran a upgrade on the default example, which fails. After tainting the security group an upgrade was smooth.

```bash
terraform taint module.runner.aws_security_group.docker_machine
```

Please can you update the PR description with a small not for the required migration

2021-07-31 09:18 UTC, npalm commented on variables.tf
> +    description      = null
```suggestion
    description      = "Allow all egress traffic for docker machine build runners"
```

2021-07-31 09:35 UTC, npalm approved these changes
Updated description, and made a smaal change in the default description of the egress rule.

2021-07-31 09:36 UTC, merged