Make check interval configurable for the runner
npalm/terraform-aws-gitlab-runner pull request #402
Opened 2021-11-01 16:19 UTC by PirminTapken

## Description

Make check interval configurable for the runner in order to reduce load on gitlab API

## Migrations required

NO

2021-11-01 16:20 UTC, PirminTapken commented
One checkmark can be added to https://github.com/npalm/terraform-aws-gitlab-runner/issues/393 by this.

2021-11-05 18:37 UTC, npalm commented on variables.tf
> +  default     = 0
Ok by me, other option could be to set the default to 3 https://docs.gitlab.com/runner/configuration/advanced-configuration.html

2021-11-05 18:37 UTC, npalm approved these changes
@PirminTapken thanks LGTM

2021-11-10 21:13 UTC, npalm commented
@PirminTapken please can you check the CI, looks like there is a format error.

2021-11-10 21:16 UTC, npalm requested changes
Fix formatting

2021-11-10 21:16 UTC, npalm commented on main.tf
> +      runners_use_private_address       = ! var.runners_use_private_address
```suggestion
      runners_use_private_address       = !var.runners_use_private_address
```

2021-11-18 22:28 UTC, npalm commented
@PirminTapken did you had time to check the review comment?

2021-12-03 12:54 UTC, vgropp commented
@npalm i stepped in to fix formatting and default to 3 seconds as @PirminTapken seems quite busy

2021-12-03 21:30 UTC, npalm approved these changes

2021-12-03 21:30 UTC, merged