feat: add runners_pull_policies
npalm/terraform-aws-gitlab-runner pull request #544
Opened 2022-09-12 21:41 UTC by gmeligio

## Description

Support multiple Docker pull policies. The pull_policy parameter allows to specify a list of pull policies. The policies in the list will be attempted in order from left to right until a pull attempt is successful, or the list is exhausted.

https://docs.gitlab.com/runner/executors/docker.html#how-pull-policies-work

## Migrations required

YES - Deprecate runners_pull_policy in favor of runners_pull_policies

## Verification

I have verified the examples (https://github.com/gmeligio/terraform-aws-gitlab-runner/actions/runs/3040680452):
- Verify examples (1.0.11, runner-default)
- Verify examples (1.0.11, runner-docker)
- Verify examples (1.0.11, runner-multi-region)
- Verify examples (1.0.11, runner-pre-registered)
- Verify examples (1.0.11, runner-public)
- Verify examples (latest, runner-default)
- Verify examples (latest, runner-docker)
- Verify examples (latest, runner-multi-region)
- Verify examples (latest, runner-pre-registered)
- Verify examples (latest, runner-public)

2022-10-10 07:04 UTC, npalm reviewed
PR looks good, but test results in runner is not started. Rebased the PR also against develop. Nu clue what the issue is right now. Not more time to dig in further. Got the following error:

```
Failed to restart gitlab-runner.service: Unit not found.

```

2022-10-10 19:41 UTC, npalm requested changes
Just went over the PR again, made some small suggestion which fixed the non starting agent.

- used `allowed_pull_policies` 
- set default for old pull_policy to empty, so by default new one is used.

2022-10-10 19:41 UTC, npalm commented on locals.tf
> +  runners_pull_policies = var.runners_pull_policy != "" ? "[${var.runners_pull_policy}]" : "[\"${join("\",\"", var.runners_pull_policies)}\"]"
```suggestion
  runners_pull_policies = var.runners_pull_policy != "" ? "[\"${var.runners_pull_policy}\"]" : "[\"${join("\",\"", var.runners_pull_policies)}\"]"
```

2022-10-10 19:41 UTC, npalm commented on template/runner-config.tpl
> +    pull_policy = ${runners_pull_policies}
```suggestion
    allowed_pull_policies = ${runners_pull_policies}
```

2022-10-10 19:41 UTC, npalm commented on variables.tf
>    default     = "always"
```suggestion
  default     = ""
```

2022-10-10 19:56 UTC, npalm approved these changes
Accepted my suggestions, tested and all good. Thanks for your contribution

2022-10-10 19:57 UTC, merged

2022-10-11 14:12 UTC, cinacio commented
> Just went over the PR again, made some small suggestion which fixed the non starting agent.
> 
>     * used `allowed_pull_policies`
> 
>     * set default for old pull_policy to empty, so by default new one is used.

First of all, thanks a lot for all the hard work on this module that makes our lives much easier!

I'm wondring about this change and the above suggestions. It's quite nice that we can now specify allowed pull policies, but if I read the docs correctly this slightly changes the behaviour of the modified directives and now prevents us from specifying a "default" pull policy for runners.

Setting `allowed_pull_policies` will define the policies that can be used in the `.gitlab-ci.yml` file or the runner configuration, but keeping `pull_policy` unset, will keep it at its default value, which is `always` according to the [GitLab runner advanced configuration documentation](https://docs.gitlab.com/15.4/runner/configuration/advanced-configuration.html#the-runnersdocker-section). Thus preventing us from modifying the "default" pull policy at the runner level, and forcing image downloads unless the policy is explicitly set in job configurations. Or am I missing something?

Wouldn't it be better to have two different directives, actually?

2022-10-13 08:06 UTC, kayman-mk commented
Also see #511

2022-10-25 07:59 UTC, cinacio commented
@npalm As I figured @gmeligio might be busy elsewhere, I took the liberty of creating PR #557 just to set `pull_policy` instead of `allowed_pull_policies`.

I hope that's alright.