Add amazonec2 userdata
npalm/terraform-aws-gitlab-runner pull request #608
Opened 2022-12-16 18:33 UTC by FelikZ

## Description

Introducing support for [amazonec2-userdata flag](https://github.com/docker/machine/blob/b170508bf44c3405e079e26d5fdffe35a64c6972/drivers/amazonec2/amazonec2.go#L284) that is not mentioned on [driver readme page](https://gitlab.com/gitlab-org/ci-cd/docker-machine/-/blob/main/docs/drivers/aws.md), but it is there and useful.

For example, it can be used to introduce swap for the runner instance or any other user command.

## Migrations required

NO - this is optional flag and defaults to empty string.

## Verification

I have verified on my own runners cluster that user script that I've added works (it creates swap in my case).

```
module "runner" {
  # source  = "npalm/gitlab-runner/aws"
  # version = "5.5.0"

  # ...

  runners_userdata = templatefile("${path.module}/../../templates/swap.tpl", {
    swap_size = "512"
  })
}
```

2022-12-16 18:34 UTC, FelikZ commented
But I have no idea how to auto-generate README.md, I think this flag should be documented. (manually edit?)

2023-01-01 16:52 UTC, kayman-mk requested changes
Good PR! Just 2 little remarks.

2023-01-01 16:52 UTC, kayman-mk commented on template/gitlab-runner.tpl
> +cat > /etc/gitlab-runner/runners_userdata.tpl <<- EOF
issue: File suffix should be `.sh` or similar as this is not a template file.

2023-01-01 16:52 UTC, kayman-mk commented on template/runner-config.tpl
> +      "amazonec2-userdata=%{ if runners_userdata != "" }/etc/gitlab-runner/runners_userdata.tpl%{ endif ~}",
chore: to be tested without specifying `runners_userdata`

2023-01-06 14:31 UTC, kayman-mk commented on template/runner-config.tpl
> +      "amazonec2-userdata=%{ if runners_userdata != "" }/etc/gitlab-runner/runners_userdata.tpl%{ endif ~}",
Successfully tested. The executors are still running. Nevertheless I had problems with one executor which was not able to update the Ubuntu system. Quite strange. Seems not to be related to this PR.

@npalm Just to be on the safe side: Could you test this as well please?

2023-01-06 14:32 UTC, kayman-mk approved these changes

2023-01-06 14:33 UTC, kayman-mk commented
@npalm See my comment above. Better you check this as well.

2023-01-07 09:40 UTC, npalm requested changes
@FelikZ thanks looks good! Please can you add the example. Which you mention in the PR to either the Readme. Or as comment in the default example. I would prefer the last one (example)

2023-01-12 14:08 UTC, kayman-mk approved these changes

2023-01-12 14:11 UTC, kayman-mk commented
Did you do a quick check without using the new variable `runners_userdata` to make sure that the agent is still able to start?

2023-01-12 16:10 UTC, kayman-mk commented
Ok, it's working. Had a test environment available and deployed your changes. It is working without `runners_userdata`.

2023-01-12 16:11 UTC, merged