ci: validate PR title
npalm/terraform-aws-gitlab-runner pull request #625
Opened 2023-01-03 09:35 UTC by kayman-mk

## Description

Adds a new workflow action which lints the title of the PR. This is to make sure that we have commits adhering to the semantic commit rules only. Otherwise Release-Please is not able to determine the next version number and will not create a release.

2023-01-03 09:40 UTC, kayman-mk commented
The following settings should be active: Settings > General > Pull Requests: Allow squash merging only. Message shouldn't be the "Default message" as this might cause problems in case there is only one commit in the branch. It should be set to something starting with "Pull request title".

Personally I prefer "Pull request title and description". Especially as we have a PR template. Would be nice to see this in the commits too.

@npalm Could you please check this?

2023-01-03 09:41 UTC, kayman-mk commented
@npalm Could you please correct the commit message of "9056fb25170d659ddcbb37291220333a8e427950" in `main`? The prefix should read `feat` instead of `fet`.

2023-01-03 12:39 UTC, npalm requested changes

2023-01-03 12:39 UTC, npalm commented on .github/workflows/lint_pr_title.yml
> +          validateSingleCommit: false
```suggestion
          validateSingleCommit: true
```
Would enable this exact for the reason mentioned in the comment

2023-01-05 22:20 UTC, npalm approved these changes

2023-01-05 22:20 UTC, merged