fix: error IAM role attachement when applying the module the first ti…
npalm/terraform-aws-gitlab-runner pull request #659
Opened 2023-01-13 11:45 UTC by npalm

## Description

fix #591

Ensure polcies attachment are don with module managed resources in case the role is managed via terraform objects. This to avoid attachments are created before the role is created. Depends on does not support dynamics, sot not an option.

## Migrations required

NO

## Verification

Failed, docker-machine is not becoming healty

2023-01-13 11:47 UTC, npalm commented
@kayman-mk Tried to fix the issue, but the docker machine is not booting yet. I have not more time to dig in, will have a look later. Or feel free to dig in as well

2023-01-18 22:50 UTC, npalm commented
@kayman-mk would you the option to rebase this PR

2023-01-19 08:05 UTC, kayman-mk commented
Merge conflicts solved.

I changed some more policies and tested the change. First apply succeeded. 👍

2023-01-19 08:09 UTC, kayman-mk requested changes

2023-01-19 08:09 UTC, kayman-mk commented on logging.tf
> +  role   = var.create_runner_iam_role ? aws_iam_role.instance[0].name : var.runner_iam_role_name
suggestion: replace `var.runner_iam_role_name`by `local.aws_iam_role_instance_name` in all changes.

The local variable respects the `var.overrides["name_iam_objects"]` which was introduced to align the names of IAM objects. The variable description says: `If unspecified then `{name_iam_objects}-instance` is used`.

2023-01-19 08:13 UTC, kayman-mk requested changes

2023-01-19 08:13 UTC, kayman-mk commented on main.tf
> +  role       = var.create_runner_iam_role ? aws_iam_role.instance[0].name : var.runner_iam_role_name
```suggestion
  role       = var.create_runner_iam_role ? aws_iam_role.instance[0].name : local.aws_iam_role_instance_name
```

2023-01-19 08:13 UTC, kayman-mk commented on logging.tf
> +  role   = var.create_runner_iam_role ? aws_iam_role.instance[0].name : var.runner_iam_role_name
```suggestion
  role   = var.create_runner_iam_role ? aws_iam_role.instance[0].name : local.aws_iam_role_instance_name
```

2023-01-19 08:13 UTC, kayman-mk commented on main.tf
> +  role       = var.create_runner_iam_role ? aws_iam_role.instance[0].name : var.runner_iam_role_name
```suggestion
  role       = var.create_runner_iam_role ? aws_iam_role.instance[0].name : local.aws_iam_role_instance_name
```

2023-01-19 08:13 UTC, kayman-mk commented on main.tf
> +  role       = var.create_runner_iam_role ? aws_iam_role.instance[0].name : var.runner_iam_role_name
```suggestion
  role       = var.create_runner_iam_role ? aws_iam_role.instance[0].name : local.aws_iam_role_instance_name
```

2023-01-19 08:13 UTC, kayman-mk commented on main.tf
> +  role       = var.create_runner_iam_role ? aws_iam_role.instance[0].name : var.runner_iam_role_name
```suggestion
  role       = var.create_runner_iam_role ? aws_iam_role.instance[0].name : local.aws_iam_role_instance_name
```

2023-01-19 08:13 UTC, kayman-mk commented on main.tf
> +  role       = var.create_runner_iam_role ? aws_iam_role.instance[0].name : var.runner_iam_role_name
```suggestion
  role       = var.create_runner_iam_role ? aws_iam_role.instance[0].name : local.aws_iam_role_instance_name
```

2023-01-19 08:13 UTC, kayman-mk commented on main.tf
> +  role       = var.create_runner_iam_role ? aws_iam_role.instance[0].name : var.runner_iam_role_name
```suggestion
  role       = var.create_runner_iam_role ? aws_iam_role.instance[0].name : local.aws_iam_role_instance_name
```

2023-01-19 08:13 UTC, kayman-mk commented on main.tf
> +  role       = var.create_runner_iam_role ? aws_iam_role.instance[0].name : var.runner_iam_role_name
```suggestion
  role       = var.create_runner_iam_role ? aws_iam_role.instance[0].name : local.aws_iam_role_instance_name
```

2023-02-23 21:19 UTC, npalm commented
@kayman-mk accepted your suggestion, PR is good to go. Please can you review the PR?

2023-02-25 15:04 UTC, npalm commented
@kayman-mk can you review the PR, should be ready to merge

2023-02-26 07:58 UTC, kayman-mk approved these changes

2023-02-26 07:59 UTC, merged